apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  namespace: nginx
  labels:
    run: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      run: nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: nginx
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: pochaakshybridapi20230911101608.azurecr.io/pochaakshybridapi:latest
        name: nginx
        resources: {}
status: {}
